version: '3.8'
services:

  # Docker connection string: postgres://postgres:postgres@localhost:5432/

  discordia:
    container_name: discordia
    build:
      dockerfile: Dockerfile
      context: "."
    restart: always
    # depends_on:
    #   - database
    ports:
      - 8000:8000

  # postgres:
  #   image: postgres
  #   restart: always
  #   environment:
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=postgres
  #   volumes:
  #     - postgres:/var/lib/postgresql/data
  #   ports:
  #     - '8080:5432'

# volumes:
#   postgres: